sudo: false
language: node_js
node_js:
  - '10'

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

script:
  - set -e
  - yarn run jest --projects jest.config.js jest.lint.config.js --maxWorkers=4 --reporters jest-silent-reporter
  - yarn build
  - set +e
